# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: maven
      # - run: mvn -B install --no-transfer-progress --file pom.xml
      - name: Run the Maven test phase
        run: mvn --batch-mode --update-snapshots test
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package