# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8, 11, 15 ]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2.1.1
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-java${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.java }}-
            maven-${{ matrix.os }}-
      - name: Install Toolchain JDK
        if: ${{ matrix.java == '8' }}
        uses: battila7/jdk-via-jabba@v1
        with:
          jdk: adopt-openj9@1.11.0-7
          javaHomeEnvironmentVariable: TOOLCHAIN_JDK
      - name: Set up Toolchain
        if: ${{ matrix.java == '8' }}
        shell: bash
        run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
                <provides>
                  <version>11</version>
                  <vendor>adopt</vendor>
                </provides>
                <configuration>
                  <jdkHome>${{ env.TOOLCHAIN_JDK }}</jdkHome>
                </configuration>
            </toolchain>
          </toolchains>
          EOF
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
      run: mvn -B package --file pom.xml
